name: CI

on:
  push:
    branches-ignore: ['ivan-integrated']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git init .
          git remote add origin ${{ github.server_url }}/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.sha }}
          git checkout FETCH_HEAD

      - name: Build Fun.Blazor (main package only)
        run: dotnet build Fun.Blazor/Fun.Blazor.fsproj -c Release --nologo

      - name: Test
        run: dotnet test Fun.Blazor.Tests/Fun.Blazor.Tests.fsproj -c Release --nologo
